// Rhyme Time: one cockney rhyming slang question a day. [slang, meaning, wrong answer, wrong answer]
export const SLANG = [
  ['Apples and pears', 'Stairs', 'Fruit bowl', 'Chairs'],
  ['Loaf of bread', 'Head', 'Sandwich', 'Bed'],
  ['Butcher\'s hook', 'A look', 'A cook', 'Meat'],
  ['Dog and bone', 'Telephone', 'Dinner', 'Home'],
  ['Trouble and strife', 'Wife', 'Knife', 'An argument'],
  ['Rosie Lee', 'Tea', 'Sea', 'A flower'],
  ['Adam and Eve', 'Believe', 'Leave', 'A garden'],
  ['Boat race', 'Face', 'Place', 'The Thames'],
  ['Plates of meat', 'Feet', 'Dinner', 'Street'],
  ['Mince pies', 'Eyes', 'Christmas', 'Lies'],
  ['Hampstead Heath', 'Teeth', 'A park', 'A wreath'],
  ['Barnet Fair', 'Hair', 'A market', 'A chair'],
  ['Whistle and flute', 'Suit', 'A band', 'Fruit'],
  ['Syrup of figs', 'Wig', 'Pudding', 'Pigs'],
  ['China plate', 'Mate', 'Crockery', 'Late'],
  ['Tea leaf', 'Thief', 'A cuppa', 'Beef'],
  ['Brown bread', 'Dead', 'Toast', 'Bed'],
  ['Bread and honey', 'Money', 'Breakfast', 'Funny'],
  ['Bubble bath', 'Laugh', 'A wash', 'Path'],
  ['Pork pies', 'Lies', 'Eyes', 'Picnic'],
  ['Frog and toad', 'Road', 'A pond', 'Load'],
  ['Jam jar', 'Car', 'Bar', 'Preserves'],
  ['Currant bun', 'Sun', 'Son', 'A cake'],
  ['Ruby Murray', 'Curry', 'A singer', 'Hurry'],
  ['Rabbit and pork', 'Talk', 'Walk', 'Stew'],
  ['Scooby Doo', 'Clue', 'A dog', 'Shoe'],
  ['Gregory Peck', 'Neck', 'Cheque', 'A film'],
  ['Pete Tong', 'Wrong', 'Song', 'A DJ'],
  ['Half inch', 'Pinch (steal)', 'Measure', 'A bench'],
  ['Kettle and hob', 'Fob watch', 'Cooker', 'A job'],
  ['Tit for tat', 'Hat', 'Cat', 'Revenge'],
  ['Titfer', 'Hat', 'A bird', 'A tip'],
  ['Daisy roots', 'Boots', 'Flowers', 'Fruits'],
  ['Pen and ink', 'Stink', 'A letter', 'Sink'],
  ['Ones and twos', 'Shoes', 'News', 'Numbers'],
  ['Skin and blister', 'Sister', 'A sore', 'Mister'],
  ['Brahms and Liszt', 'Drunk (pissed)', 'Composers', 'Missed'],
  ['Lionel Blairs', 'Flares', 'Stairs', 'A dancer'],
  ['Mutt and Jeff', 'Deaf', 'Two dogs', 'Chef'],
  ['Khyber Pass', 'Backside', 'A mountain', 'Grass'],
  ['Cream crackered', 'Knackered', 'Biscuits', 'Cracked'],
  ['Hank Marvin', 'Starving', 'A guitarist', 'Carving'],
  ['Sausage and mash', 'Cash', 'Dinner', 'A crash'],
  ['Lady Godiva', 'Fiver', 'A horse', 'Driver'],
  ['Cockle', 'Tenner (cock and hen)', 'Shellfish', 'A wink'],
  ['Oily rag', 'Cigarette (fag)', 'A duster', 'Bag'],
  ['Pig\'s ear', 'Beer', 'A mess', 'Here'],
  ['Vera Lynn', 'Gin', 'A singer', 'Win'],
  ['Aris (Aristotle)', 'Bottle', 'A thinker', 'Model'],
  ['Battle cruiser', 'Boozer (pub)', 'A warship', 'A loser'],
  ['Rub-a-dub', 'Pub', 'A bath', 'Club'],
  ['Mickey Mouse', 'House', 'A cartoon', 'Grouse'],
  ['Bees and honey', 'Money', 'Garden', 'Sunny'],
  ['Weasel and stoat', 'Coat', 'Animals', 'Boat'],
  ['Round the houses', 'Trousers', 'A walk', 'Blouses'],
  ['Minces', 'Eyes', 'Pies', 'Meat'],
  ['Raspberry tart', 'Fart', 'Dessert', 'A heart'],
  ['Chalk Farm', 'Arm', 'A station', 'A barn'],
  ['Bottle and glass', 'Backside (arse)', 'A drink', 'Grass'],
  ['Twist and twirl', 'Girl', 'A dance', 'Pearl'],
];

export function rhymeFor(dateStr, hash) {
  const q = SLANG[hash % SLANG.length];
  const opts = [q[1], q[2], q[3]];
  // stable shuffle by hash
  const order = [0, 1, 2].sort((a, b) => ((hash >> (a * 3)) & 7) - ((hash >> (b * 3)) & 7));
  return { slang: q[0], answer: q[1], options: order.map((k) => opts[k]) };
}
