// Generated from tools/voice-lines.json by tools/make_voice.sh. Clips live in audio/voice/<id>.mp3
export const VOICE_LINES = [{"id":"good-1","group":"good","ron":false,"text":"Tidy!"},
  {"id":"good-2","group":"good","ron":false,"text":"Pukka!"},
  {"id":"good-3","group":"good","ron":false,"text":"Nice one!"},
  {"id":"good-4","group":"good","ron":false,"text":"Handsome!"},
  {"id":"big-1","group":"big","ron":false,"text":"Blinding!"},
  {"id":"big-2","group":"big","ron":false,"text":"Lovely jubbly!"},
  {"id":"big-3","group":"big","ron":false,"text":"Cor, look at that!"},
  {"id":"huge-1","group":"huge","ron":false,"text":"Would you Adam and Eve it!"},
  {"id":"huge-2","group":"huge","ron":false,"text":"Cor blimey, look at that lot!"},
  {"id":"huge-3","group":"huge","ron":false,"text":"Well I never! Look at it go!"},
  {"id":"cab-1","group":"cab","ron":false,"text":"Taxi!"},
  {"id":"cab-2","group":"cab","ron":false,"text":"Where to, guv?"},
  {"id":"ben-1","group":"ben","ron":false,"text":"Big Ben's having a go!"},
  {"id":"button-1","group":"button","ron":false,"text":"Pearly button! Get in!"},
  {"id":"wood-1","group":"wood","ron":false,"text":"Bowl it!"},
  {"id":"wood-2","group":"wood","ron":false,"text":"Right on the jack!"},
  {"id":"win-1","group":"win","ron":false,"text":"Lovely jubbly!"},
  {"id":"win-2","group":"win","ron":false,"text":"Diamond geezer!"},
  {"id":"win-3","group":"win","ron":false,"text":"Get the Rosie Lee on, you've earned it."},
  {"id":"win-4","group":"win","ron":false,"text":"Blinding. Absolutely blinding."},
  {"id":"win-5","group":"win","ron":false,"text":"Proper job, that."},
  {"id":"win-ron-1","group":"win","ron":true,"text":"Blinding, Ron. Absolutely blinding."},
  {"id":"win-ron-2","group":"win","ron":true,"text":"Go on, Ron! Diamond geezer!"},
  {"id":"hard-1","group":"hard","ron":false,"text":"Proper hard, proper done!"},
  {"id":"three-1","group":"three","ron":false,"text":"Three stars! You're a diamond."},
  {"id":"three-ron-1","group":"three","ron":true,"text":"Three stars! You're a diamond, Ron."},
  {"id":"lose-1","group":"lose","ron":false,"text":"You're 'avin' a bubble! Go on, one more."},
  {"id":"lose-2","group":"lose","ron":false,"text":"Not your day, son. Another go?"},
  {"id":"lose-3","group":"lose","ron":false,"text":"Gawd help us. Go on, 'ave another crack."},
  {"id":"lose-ron-1","group":"lose","ron":true,"text":"So close, Ron! Don't give up now."},
  {"id":"hint-1","group":"hint","ron":false,"text":"'Ave a butcher's, there's one right there."},
  {"id":"hint-2","group":"hint","ron":false,"text":"Use your loaf!"},
  {"id":"hint-ron-1","group":"hint","ron":true,"text":"Use your loaf, Ron!"},
  {"id":"start-1","group":"start","ron":false,"text":"Right, let's 'ave it!"},
  {"id":"start-2","group":"start","ron":false,"text":"Off we go, guv'nor."},
  {"id":"start-3","group":"start","ron":false,"text":"Mind the match!"},
  {"id":"low-1","group":"low","ron":false,"text":"Five moves left. Get your skates on!"},
  {"id":"toucher-1","group":"toucher","ron":false,"text":"Toucher finish! Let's 'ave 'em!"},
  {"id":"icecream-1","group":"icecream","ron":false,"text":"Ice cream van! Quick, tap it!"},
  {"id":"pigeon-1","group":"pigeon","ron":false,"text":"Oi! Catch that pigeon!"},
  {"id":"happy-1","group":"happy","ron":false,"text":"It's Happy Hour down the Ronnie Arms! Double points!"},
  {"id":"orders-1","group":"orders","ron":false,"text":"Last orders! Five minutes left of Happy Hour."},
  {"id":"bighour-1","group":"bighour","ron":false,"text":"Big Ben's struck the hour. Free Big Ben, on the house!"},
  {"id":"swag-1","group":"swag","ron":false,"text":"Bag of swag! Go on, open it."},
  {"id":"streak-1","group":"streak","ron":false,"text":"You're on a roll!"},
  {"id":"streak-ron-1","group":"streak","ron":true,"text":"You're on a roll, Ron!"},
  {"id":"welcome-1","group":"welcome","ron":false,"text":"Alright, me old china? Welcome to the Manor."},
  {"id":"welcome-ron-1","group":"welcome","ron":true,"text":"Alright, Ron? Welcome to the Manor, guv'nor."},
  {"id":"kettle-1","group":"kettle","ron":false,"text":"You've been at it two hours. Kettle on?"},
  {"id":"kettle-ron-1","group":"kettle","ron":true,"text":"You've been at it two hours, Ron. Kettle on?"},
  {"id":"nightbus-1","group":"nightbus","ron":false,"text":"All aboard the Night Bus!"},
  {"id":"daily-1","group":"daily","ron":false,"text":"Here's today's Daily Ronnie. Let's see what you've got."},
  {"id":"rhymeyes-1","group":"rhymeyes","ron":false,"text":"Spot on!"},
  {"id":"rhymeno-1","group":"rhymeno","ron":false,"text":"Close, but no cigar."},
  {"id":"zone-1","group":"zone","ron":false,"text":"That's the whole zone done. Next stop!"},
  {"id":"crown-1","group":"crown","ron":false,"text":"Top of the Manor! Who's the guv'nor now?"},
  {"id":"club-1","group":"club","ron":false,"text":"Club Night on the green. Let's roll!"},
  {"id":"moves-1","group":"moves","ron":false,"text":"Five more moves, on the house!"}];
