// Writes sw.js with every file the game needs, so it plays offline. Run after changing files.
import fs from 'node:fs';
import path from 'node:path';
const files = ['./', 'index.html', 'manifest.webmanifest'];
const walk = (d) => fs.readdirSync(d).flatMap((f) => { const p = path.join(d, f); return fs.statSync(p).isDirectory() ? walk(p) : [p]; });
for (const d of ['css', 'js', 'data', 'audio', 'icons']) if (fs.existsSync(d)) files.push(...walk(d).filter((f) => !f.endsWith('.DS_Store')));
const version = Date.now().toString(36);
fs.writeFileSync('sw.js', `// Generated by tools/make_sw.mjs. Caches the whole game so it plays offline.
const CACHE = 'ronnies-manor-${version}';
const FILES = ${JSON.stringify(files)};
self.addEventListener('install', (e) => { e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting())); });
self.addEventListener('activate', (e) => { e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', (e) => {
  const u = new URL(e.request.url);
  if (e.request.method !== 'GET' || u.hostname.includes('script.google')) return; // leaderboard goes straight to the network
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then((hit) => {
    const net = fetch(e.request).then((r) => { if (r.ok || r.type === 'opaque') { const cp = r.clone(); caches.open(CACHE).then((c) => c.put(e.request, cp)); } return r; }).catch(() => hit);
    return hit || net;
  }));
});
`);
console.log('sw.js:', files.length, 'files, cache', version);
